### ISSUE TITLE
Tokens fra idporten mangler client_id selv om man sender det som queryparam

### ISSUE THREAD

**Issue by tanettrimas** [navikt/fakedings#1]
Burde gjøres slik at dette kan settes som en claim. Dette er normalt med i alle access tokens fra dem. 

Ref: https://docs.digdir.no/oidc_protocol_access_token.html

Denne jwt generert fra [linken](https://fakedings.dev-gcp.nais.io/fake/idporten?client_id=123) mangler client_id.

**Comment by tronghn** [comment]
Fixed in [f8403bf](https://github.com/navikt/fakedings/commit/f8403bf7bd9c664ec07a60418d466508009392a4)(albeit a couple years later)
