### ISSUE TITLE
JVM 2.1.0 tryner appen

### ISSUE THREAD

**Issue by fredrikmork** [navikt/fakedings#19]
Jeg har ikke tilgang til å gjøre en PR så lager en issue og varsler om caset.
Gikk tilbake til commit-en før denne endringen og da funket det som det skulle.

`kotlin("jvm") version "2.0.21"` fungerer fortsatt

**Comment by tronghn** [comment]
Har du en feilmelding som sier noe om feilen?

Ellers så henger jeg ikke helt med her, kloner dere dette repoet og kjører den opp rett fra master? Mergen til 2.1.0 har ikke blitt deployet.

**Comment by tronghn** [comment]
Det er en feil i Kotlinter som bundler med mismatchende versjon av kompilatoren. Jeg kan jo selvsagt rulle tilbake til 2.0.21, men dette prosjektet er ikke laget for å kjøres lokalt - hvorfor ikke bare bruke endepunktene som er nevnt i README?

**Comment by tronghn** [comment]
Fikset med https://github.com/navikt/fakedings/commit/91fa0c53408a6f637ffb0c3ce8b009dfe9133ce3.
